using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security;
using System.Security.Cryptography;
using System.Text;

using UnityEditor;
using UnityEditor.Compilation;
using CompilationAssembly = UnityEditor.Compilation.Assembly;

namespace Locus
{
    /// Generates a complete MSBuild workspace directly from Unity's compilation
    /// graph. This keeps Locus usable as the selected external editor even when
    /// no Visual Studio, Rider, or VS Code integration package is installed.
    internal static class LocusProjectFileGenerator
    {
        private const string NewLine = "\r\n";
        private const string CSharpProjectTypeGuid = "FAE04EC0-301F-11D3-BF4B-00C04F79EFBC";
        private static readonly UTF8Encoding Utf8WithoutBom = new UTF8Encoding(false);

        private sealed class Project
        {
            internal CompilationAssembly Assembly;
            internal string Name;
            internal string FileName;
            internal string Guid;
        }

        internal static void Generate()
        {
            string projectRoot = Path.GetFullPath(Path.Combine(UnityEngine.Application.dataPath, ".."));
            List<Project> projects = CompilationPipeline
                .GetAssemblies(AssembliesType.Editor)
                .Where(HasCSharpSource)
                .OrderBy(assembly => assembly.name, StringComparer.OrdinalIgnoreCase)
                .Select(assembly => new Project
                {
                    Assembly = assembly,
                    Name = assembly.name,
                    FileName = SafeFileName(assembly.name) + ".csproj",
                    Guid = StableGuid(assembly.name),
                })
                .ToList();

            if (projects.Count == 0)
                throw new InvalidOperationException("Unity reported no C# script assemblies");

            var projectsByName = projects.ToDictionary(
                project => project.Name,
                StringComparer.OrdinalIgnoreCase);

            foreach (Project project in projects)
            {
                string path = Path.Combine(projectRoot, project.FileName);
                string content = BuildProject(projectRoot, project, projectsByName);
                content = InvokeContentCallbacks("OnGeneratedCSProject", path, content);
                WriteIfChanged(path, content);
            }

            string solutionPath = Path.Combine(
                projectRoot,
                SafeFileName(new DirectoryInfo(projectRoot).Name) + ".sln");
            string solution = InvokeContentCallbacks(
                "OnGeneratedSlnSolution",
                solutionPath,
                BuildSolution(projects));
            WriteIfChanged(solutionPath, solution);
            InvokeGeneratedCallbacks();
        }

        private static bool HasCSharpSource(CompilationAssembly assembly)
        {
            return assembly != null
                && assembly.sourceFiles != null
                && assembly.sourceFiles.Any(path =>
                    path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase));
        }

        private static string BuildProject(
            string projectRoot,
            Project project,
            IDictionary<string, Project> projectsByName)
        {
            CompilationAssembly assembly = project.Assembly;
            object compilerOptions = assembly.compilerOptions;
            bool allowUnsafe = ReadBoolProperty(compilerOptions, "AllowUnsafeCode");
            string rootNamespace = ReadStringProperty(assembly, "rootNamespace");
            if (string.IsNullOrEmpty(rootNamespace))
                rootNamespace = EditorSettings.projectGenerationRootNamespace ?? "";

            var builder = new StringBuilder();
            builder.Append("<?xml version=\"1.0\" encoding=\"utf-8\"?>").Append(NewLine);
            builder.Append("<Project ToolsVersion=\"4.0\" DefaultTargets=\"Build\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">").Append(NewLine);
            builder.Append("  <!-- Generated by Locus from Unity's CompilationPipeline. -->").Append(NewLine);
            builder.Append("  <PropertyGroup>").Append(NewLine);
            AppendElement(builder, "Configuration", "Debug", " Condition=\" '$(Configuration)' == '' \"");
            AppendElement(builder, "Platform", "AnyCPU", " Condition=\" '$(Platform)' == '' \"");
            AppendElement(builder, "ProjectGuid", "{" + project.Guid + "}");
            AppendElement(builder, "OutputType", "Library");
            AppendElement(builder, "RootNamespace", rootNamespace);
            AppendElement(builder, "AssemblyName", assembly.name);
            AppendElement(builder, "TargetFrameworkVersion", "v4.7.1");
            AppendElement(builder, "LangVersion", "latest");
            AppendElement(builder, "FileAlignment", "512");
            builder.Append("  </PropertyGroup>").Append(NewLine);
            builder.Append("  <PropertyGroup Condition=\" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' \">").Append(NewLine);
            AppendElement(builder, "DebugSymbols", "true");
            AppendElement(builder, "DebugType", "full");
            AppendElement(builder, "Optimize", "false");
            AppendElement(builder, "OutputPath", Path.Combine("Temp", "bin", "Debug", assembly.name) + Path.DirectorySeparatorChar);
            AppendElement(builder, "DefineConstants", string.Join(";", assembly.defines ?? new string[0]));
            AppendElement(builder, "WarningLevel", "4");
            AppendElement(builder, "NoWarn", "0169;0649");
            AppendElement(builder, "AllowUnsafeBlocks", allowUnsafe ? "true" : "false");
            builder.Append("  </PropertyGroup>").Append(NewLine);
            builder.Append("  <PropertyGroup>").Append(NewLine);
            AppendElement(builder, "NoConfig", "true");
            AppendElement(builder, "NoStdLib", "true");
            AppendElement(builder, "AddAdditionalExplicitAssemblyReferences", "false");
            AppendElement(builder, "ImplicitlyExpandNETStandardFacades", "false");
            AppendElement(builder, "ImplicitlyExpandDesignTimeFacades", "false");
            builder.Append("  </PropertyGroup>").Append(NewLine);

            AppendItems(
                builder,
                "Compile",
                assembly.sourceFiles
                    .Where(path => path.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
                    .Select(path => ProjectPath(projectRoot, path)));

            var binaryReferences = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (string reference in assembly.compiledAssemblyReferences ?? new string[0])
                AddReference(binaryReferences, projectRoot, reference);
            foreach (CompilationAssembly reference in assembly.assemblyReferences ?? new CompilationAssembly[0])
            {
                if (!projectsByName.ContainsKey(reference.name))
                    AddReference(binaryReferences, projectRoot, reference.outputPath);
            }

            builder.Append("  <ItemGroup>").Append(NewLine);
            foreach (string reference in binaryReferences.OrderBy(path => path, StringComparer.OrdinalIgnoreCase))
            {
                builder.Append("    <Reference Include=\"")
                    .Append(Xml(Path.GetFileNameWithoutExtension(reference)))
                    .Append("\">").Append(NewLine);
                builder.Append("      <HintPath>").Append(Xml(MsBuildEscape(reference))).Append("</HintPath>").Append(NewLine);
                builder.Append("      <Private>False</Private>").Append(NewLine);
                builder.Append("    </Reference>").Append(NewLine);
            }
            builder.Append("  </ItemGroup>").Append(NewLine);

            builder.Append("  <ItemGroup>").Append(NewLine);
            foreach (CompilationAssembly reference in assembly.assemblyReferences ?? new CompilationAssembly[0])
            {
                Project referencedProject;
                if (!projectsByName.TryGetValue(reference.name, out referencedProject))
                    continue;
                builder.Append("    <ProjectReference Include=\"")
                    .Append(Xml(MsBuildEscape(referencedProject.FileName)))
                    .Append("\">").Append(NewLine);
                builder.Append("      <Project>{").Append(referencedProject.Guid).Append("}</Project>").Append(NewLine);
                builder.Append("      <Name>").Append(Xml(referencedProject.Name)).Append("</Name>").Append(NewLine);
                builder.Append("    </ProjectReference>").Append(NewLine);
            }
            builder.Append("  </ItemGroup>").Append(NewLine);

            AppendItems(builder, "Analyzer", ReadStringArrayProperty(compilerOptions, "RoslynAnalyzerDllPaths"));
            AppendItems(builder, "AdditionalFiles", ReadStringArrayProperty(compilerOptions, "RoslynAdditionalFilePaths"));
            string ruleset = ReadStringProperty(compilerOptions, "RoslynAnalyzerRulesetPath");
            if (!string.IsNullOrEmpty(ruleset))
            {
                builder.Append("  <PropertyGroup>").Append(NewLine);
                AppendElement(builder, "CodeAnalysisRuleSet", ProjectPath(projectRoot, ruleset));
                builder.Append("  </PropertyGroup>").Append(NewLine);
            }
            string analyzerConfig = ReadStringProperty(compilerOptions, "AnalyzerConfigPath");
            if (!string.IsNullOrEmpty(analyzerConfig))
                AppendItems(builder, "EditorConfigFiles", new[] { ProjectPath(projectRoot, analyzerConfig) });

            builder.Append("  <Import Project=\"$(MSBuildToolsPath)\\Microsoft.CSharp.targets\" />").Append(NewLine);
            builder.Append("</Project>").Append(NewLine);
            return builder.ToString();
        }

        private static string BuildSolution(IList<Project> projects)
        {
            var builder = new StringBuilder();
            builder.Append("Microsoft Visual Studio Solution File, Format Version 12.00").Append(NewLine);
            builder.Append("# Visual Studio Version 17").Append(NewLine);
            foreach (Project project in projects)
            {
                builder.Append("Project(\"{").Append(CSharpProjectTypeGuid).Append("}\") = \"")
                    .Append(project.Name).Append("\", \"").Append(project.FileName).Append("\", \"{")
                    .Append(project.Guid).Append("}\"").Append(NewLine);
                builder.Append("EndProject").Append(NewLine);
            }
            builder.Append("Global").Append(NewLine);
            builder.Append("\tGlobalSection(SolutionConfigurationPlatforms) = preSolution").Append(NewLine);
            builder.Append("\t\tDebug|Any CPU = Debug|Any CPU").Append(NewLine);
            builder.Append("\t\tRelease|Any CPU = Release|Any CPU").Append(NewLine);
            builder.Append("\tEndGlobalSection").Append(NewLine);
            builder.Append("\tGlobalSection(ProjectConfigurationPlatforms) = postSolution").Append(NewLine);
            foreach (Project project in projects)
            {
                builder.Append("\t\t{").Append(project.Guid).Append("}.Debug|Any CPU.ActiveCfg = Debug|Any CPU").Append(NewLine);
                builder.Append("\t\t{").Append(project.Guid).Append("}.Debug|Any CPU.Build.0 = Debug|Any CPU").Append(NewLine);
                builder.Append("\t\t{").Append(project.Guid).Append("}.Release|Any CPU.ActiveCfg = Release|Any CPU").Append(NewLine);
                builder.Append("\t\t{").Append(project.Guid).Append("}.Release|Any CPU.Build.0 = Release|Any CPU").Append(NewLine);
            }
            builder.Append("\tEndGlobalSection").Append(NewLine);
            builder.Append("EndGlobal").Append(NewLine);
            return builder.ToString();
        }

        private static void AppendElement(StringBuilder builder, string name, string value, string attributes = "")
        {
            builder.Append("    <").Append(name).Append(attributes).Append(">")
                .Append(Xml(value ?? "")).Append("</").Append(name).Append(">").Append(NewLine);
        }

        private static void AppendItems(StringBuilder builder, string name, IEnumerable<string> paths)
        {
            string[] items = (paths ?? Enumerable.Empty<string>())
                .Where(path => !string.IsNullOrWhiteSpace(path))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
                .ToArray();
            if (items.Length == 0)
                return;
            builder.Append("  <ItemGroup>").Append(NewLine);
            foreach (string path in items)
            {
                builder.Append("    <").Append(name).Append(" Include=\"")
                    .Append(Xml(MsBuildEscape(path))).Append("\" />").Append(NewLine);
            }
            builder.Append("  </ItemGroup>").Append(NewLine);
        }

        private static void AddReference(ISet<string> references, string projectRoot, string path)
        {
            if (!string.IsNullOrWhiteSpace(path))
                references.Add(ProjectPath(projectRoot, path));
        }

        private static string ProjectPath(string projectRoot, string path)
        {
            if (string.IsNullOrWhiteSpace(path))
                return "";
            string normalized = path.Replace('/', Path.DirectorySeparatorChar);
            if (Path.IsPathRooted(normalized))
                return Path.GetFullPath(normalized);
            return normalized.TrimStart(Path.DirectorySeparatorChar);
        }

        private static string SafeFileName(string value)
        {
            var invalid = new HashSet<char>(Path.GetInvalidFileNameChars());
            string result = new string((value ?? "UnityProject")
                .Select(character => invalid.Contains(character) ? '_' : character)
                .ToArray());
            return string.IsNullOrWhiteSpace(result) ? "UnityProject" : result;
        }

        private static string StableGuid(string value)
        {
            using (MD5 md5 = MD5.Create())
            {
                byte[] bytes = md5.ComputeHash(Encoding.UTF8.GetBytes(value ?? ""));
                return new Guid(bytes).ToString("D").ToUpperInvariant();
            }
        }

        private static string MsBuildEscape(string value)
        {
            return (value ?? "").Replace("%", "%25").Replace(";", "%3B");
        }

        private static string Xml(string value)
        {
            return SecurityElement.Escape(value ?? "") ?? "";
        }

        private static bool ReadBoolProperty(object target, string name)
        {
            object value = ReadProperty(target, name);
            return value is bool && (bool)value;
        }

        private static string ReadStringProperty(object target, string name)
        {
            return ReadProperty(target, name) as string ?? "";
        }

        private static string[] ReadStringArrayProperty(object target, string name)
        {
            return ReadProperty(target, name) as string[] ?? new string[0];
        }

        private static object ReadProperty(object target, string name)
        {
            if (target == null)
                return null;
            PropertyInfo property = target.GetType().GetProperty(
                name,
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
            return property != null ? property.GetValue(target, null) : null;
        }

        private static string InvokeContentCallbacks(string name, string path, string content)
        {
            foreach (Type type in TypeCache.GetTypesDerivedFrom<AssetPostprocessor>())
            {
                MethodInfo method = type.GetMethod(
                    name,
                    BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                if (method == null)
                    continue;
                try
                {
                    object result = method.Invoke(null, new object[] { path, content });
                    if (method.ReturnType == typeof(string) && result is string)
                        content = (string)result;
                }
                catch (Exception ex)
                {
                    Exception cause = ex.InnerException ?? ex;
                    UnityEngine.Debug.LogWarning(
                        "[Locus] " + name + " callback failed in " + type.FullName + ": " + cause.Message);
                }
            }
            return content;
        }

        private static void InvokeGeneratedCallbacks()
        {
            foreach (Type type in TypeCache.GetTypesDerivedFrom<AssetPostprocessor>())
            {
                MethodInfo method = type.GetMethod(
                    "OnGeneratedCSProjectFiles",
                    BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
                if (method == null)
                    continue;
                try
                {
                    method.Invoke(null, new object[0]);
                }
                catch (Exception ex)
                {
                    Exception cause = ex.InnerException ?? ex;
                    UnityEngine.Debug.LogWarning(
                        "[Locus] OnGeneratedCSProjectFiles callback failed in "
                        + type.FullName + ": " + cause.Message);
                }
            }
        }

        private static void WriteIfChanged(string path, string content)
        {
            if (File.Exists(path) && string.Equals(File.ReadAllText(path), content, StringComparison.Ordinal))
                return;
            File.WriteAllText(path, content, Utf8WithoutBom);
        }
    }
}
